projects:
  CSWebsite:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: eu-west-2
        apiId: mikay6ddcjc2dn36657ar64df4
        maxDepth: 2
extensions:
  amplify:
    version: 3
